name: Push Main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-ios-beta:
    name: Deploy iOS Beta
    runs-on: macos-latest
    environment: beta
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn install

      - name: Run iOS Beta
        run: yarn ios:beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  deploy-android-beta:
    name: Deploy Android Beta
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn install

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Android Beta
        run: yarn android:beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ANDROID_PLAY_JSON_KEY: ${{ secrets.ANDROID_PLAY_JSON_KEY }}
